version: "3.6"

services:

  postgres:

    image: postgres:11.7-alpine

    ports:

      - 6543:5432 

    environment:

      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
