name: deploy miaudote

on:
  push:
    branches: [infra/deployment-aws]

jobs:
  build:
    runs-on: [self-hosted, aws-ec2]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t anacarolinast/miaudote .
      - name: Publicar a imagem da aplicação no Docker Hub
        run: docker push anacarolinast/miaudote:latest

  deploy:
    needs: build
    runs-on: [self-hosted, aws-ec2]
    steps:
      - name: Create Docker network (optional)
        run: docker network create my-net || true

      - name: Pull the latest image
        run: docker pull anacarolinast/miaudote:latest

      - name: Deploy application
        run: |
          docker run -d \
            --name miaudote \
            --network my-net \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
            -p 3000:3000 \
            anacarolinast/miaudote:latest

